// <auto-generated />
using Labb_3_bygga_ett_API_SUT25_avancerad_dotnet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Migrations
{
    [DbContext(typeof(InterestDBContext))]
    [Migration("20260422093026_seeddata_updatedrelations")]
    partial class seeddata_updatedrelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sport med lag och boll",
                            Title = "Fotboll"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skapa program och system",
                            Title = "Programmering"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Laga mat och testa recept",
                            Title = "Matlagning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spela datorspel",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Upptäcka nya platser",
                            Title = "Resor"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lyssna och skapa musik",
                            Title = "Musik"
                        });
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Anna",
                            LastName = "Svensson",
                            Phone = 111111
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Björn",
                            LastName = "Karlsson",
                            Phone = 222222
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Cecilia",
                            LastName = "Lind",
                            Phone = 333333
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "David",
                            LastName = "Persson",
                            Phone = 444444
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Elin",
                            LastName = "Johansson",
                            Phone = 555555
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Filip",
                            LastName = "Berg",
                            Phone = 666666
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Greta",
                            LastName = "Holm",
                            Phone = 777777
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Hugo",
                            LastName = "Sand",
                            Phone = 888888
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Ida",
                            LastName = "Ek",
                            Phone = 999999
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Johan",
                            LastName = "Ström",
                            Phone = 101010
                        });
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.PersonInterest", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("personInterests");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 1,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 1,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 4
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 6
                        },
                        new
                        {
                            PersonId = 4,
                            InterestId = 4
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 6
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 4
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 6
                        },
                        new
                        {
                            PersonId = 8,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 9,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 9,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 10,
                            InterestId = 4
                        });
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("WebSiteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("websites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1,
                            WebSiteURL = "https://fotboll.se"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 3,
                            PersonId = 1,
                            WebSiteURL = "https://recept.nu"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 2,
                            PersonId = 2,
                            WebSiteURL = "https://stackoverflow.com"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            PersonId = 2,
                            WebSiteURL = "https://steamcommunity.com"
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 1,
                            PersonId = 3,
                            WebSiteURL = "https://uefa.com"
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 2,
                            PersonId = 3,
                            WebSiteURL = "https://github.com"
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 4,
                            PersonId = 4,
                            WebSiteURL = "https://ign.com"
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 3,
                            PersonId = 5,
                            WebSiteURL = "https://tasteline.se"
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 5,
                            PersonId = 5,
                            WebSiteURL = "https://lonelyplanet.com"
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 2,
                            PersonId = 6,
                            WebSiteURL = "https://unity.com"
                        },
                        new
                        {
                            Id = 11,
                            InterestId = 5,
                            PersonId = 6,
                            WebSiteURL = "https://travelguide.com"
                        },
                        new
                        {
                            Id = 12,
                            InterestId = 1,
                            PersonId = 7,
                            WebSiteURL = "https://svenskfotboll.se"
                        },
                        new
                        {
                            Id = 13,
                            InterestId = 2,
                            PersonId = 8,
                            WebSiteURL = "https://w3schools.com"
                        },
                        new
                        {
                            Id = 14,
                            InterestId = 3,
                            PersonId = 9,
                            WebSiteURL = "https://koket.se"
                        },
                        new
                        {
                            Id = 15,
                            InterestId = 1,
                            PersonId = 10,
                            WebSiteURL = "https://fifa.com"
                        },
                        new
                        {
                            Id = 16,
                            InterestId = 2,
                            PersonId = 10,
                            WebSiteURL = "https://dotnet.microsoft.com"
                        });
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.PersonInterest", b =>
                {
                    b.HasOne("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", "Interest")
                        .WithMany("personInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Website", b =>
                {
                    b.HasOne("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", "Interest")
                        .WithMany("Websites")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Person", "Person")
                        .WithMany("Websites")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", b =>
                {
                    b.Navigation("Websites");

                    b.Navigation("personInterests");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Person", b =>
                {
                    b.Navigation("PersonInterests");

                    b.Navigation("Websites");
                });
#pragma warning restore 612, 618
        }
    }
}
