// <auto-generated />
using System;
using Labb_3_bygga_ett_API_SUT25_avancerad_dotnet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Migrations
{
    [DbContext(typeof(InterestDBContext))]
    [Migration("20260420194927_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("interests");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("WebSiteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.ToTable("websites");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", b =>
                {
                    b.HasOne("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Person", null)
                        .WithMany("interests")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Website", b =>
                {
                    b.HasOne("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", null)
                        .WithMany("websites")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Interest", b =>
                {
                    b.Navigation("websites");
                });

            modelBuilder.Entity("Labb_3_bygga_ett_API_SUT25_avancerad_dotnet.Person", b =>
                {
                    b.Navigation("interests");
                });
#pragma warning restore 612, 618
        }
    }
}
